#######################################################################
# Lite SQLCI-style client for the native T4 protocol.
#######################################################################

CPPSRC := TrafodionLiteSqlciClientMain.cpp
TARGET := trafodion-lite-client
NO_GLOBAL_SYS_LIBS := 1
SYS_LIBS += -pthread -lreadline
SRCPATH := bin
