#######################################################################
# LocalLite SQLCI-style client for the native T4 protocol.
#######################################################################

CPPSRC := NativeLiteSqlciClientMain.cpp
TARGET := nativelite-client
NO_GLOBAL_SYS_LIBS := 1
SYS_LIBS += -pthread -lreadline
SRCPATH := bin
